"""
QA training pairs with Claude CLI (Opus 4.5) as judge.

Reads pairs JSONL, sends each (question, chunk_text) to Claude with a strict rubric,
gets back JSON with answerability/realism/specificity/complexity scores.

Resume-safe, concurrent, writes per-pair JSONL + summary stats.

Usage:
    python qa_pairs_claude.py \
        --pairs D:\_gpu_rig_ai\eval\training_pairs\pairs_2000_20260422.jsonl \
        --out   D:\_gpu_rig_ai\eval\training_pairs\qa_claude_opus.jsonl \
        --sample 300 --workers 4
"""
from __future__ import annotations
import argparse, json, os, random, re, subprocess, sys, time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from threading import Lock


RUBRIC = """You are grading a (question, source_chunk) training pair for a retrieval system over Indian indirect-tax law (CBIC: GST, Customs, Central Excise, Service Tax).

The pair was generated by Gemini from this chunk — the question is supposed to be something a tax practitioner might ask, for which the chunk is the correct authoritative source.

Your job: grade the pair on four dimensions. Be strict — we will filter out bad pairs.

## Rubric
- **answerable** (0/1): Does this chunk contain sufficient information to actually answer the question? 1 if a practitioner reading ONLY this chunk could give a defensible answer. 0 if the chunk merely mentions the topic or is tangential.
- **realistic** (0/1): Would a real Indian tax practitioner actually phrase this question this way? 1 = sounds like a CA/advocate asked it. 0 = sounds like a textbook exercise or too-generic academic question.
- **specific** (0/1): Is this question semantically specific to THIS chunk, or could it be answered by any of dozens of other chunks? 1 = specific. 0 = generic (bad for retrieval training).
- **complexity** (low/medium/high):
  - low = direct lookup (one rate, one date, one definition)
  - medium = applying a rule or connecting 2-3 entities to answer a scenario
  - high = multi-step reasoning, cross-act interaction, multiple parties/jurisdictions, or legal interpretation

## Output
Return ONLY this JSON, no markdown fences, no prose:
{"answerable": 0|1, "realistic": 0|1, "specific": 0|1, "complexity": "low|medium|high", "reason": "<one sentence explaining any 0 scores or uncertainty>"}

---

QUESTION:
{question}

SOURCE CHUNK:
{chunk}

---

Return only the JSON object."""


def _resolve_claude_cmd() -> str:
    """Windows needs explicit claude.cmd path."""
    if os.name == "nt":
        candidate = Path(os.environ.get("APPDATA", "")) / "npm" / "claude.cmd"
        if candidate.exists():
            return str(candidate)
    return "claude"


CLAUDE_CMD = _resolve_claude_cmd()


def call_claude(prompt: str, model: str = "opus", timeout: int = 120) -> str | None:
    env = os.environ.copy()
    env.pop("CLAUDECODE", None)
    env.pop("CLAUDE_CODE_ENTRYPOINT", None)
    try:
        r = subprocess.run(
            [CLAUDE_CMD, "-p", "--output-format", "json", "--model", model],
            env=env, shell=False, input=prompt, capture_output=True, text=True,
            timeout=timeout, encoding="utf-8", errors="replace",
        )
        if r.returncode != 0:
            return None
        # Parse JSON envelope, extract "result" (Claude wraps in ```json fences sometimes)
        try:
            env_out = json.loads(r.stdout)
            return env_out.get("result", "").strip()
        except Exception:
            return r.stdout.strip()
    except Exception:
        return None


def parse_json(text: str) -> dict | None:
    if not text: return None
    # strip fences
    t = re.sub(r"^```(?:json)?\s*|\s*```$", "", text.strip(), flags=re.MULTILINE)
    try: return json.loads(t)
    except Exception: pass
    # find first {...} block
    m = re.search(r"\{[\s\S]*\}", t)
    if m:
        try: return json.loads(m.group(0))
        except Exception: return None
    return None


def grade_pair(record: dict, q: dict, model: str) -> dict:
    prompt = RUBRIC.replace("{question}", q["q"]).replace("{chunk}", record["text"][:3500])
    out = call_claude(prompt, model=model)
    parsed = parse_json(out) if out else None
    return {
        "chunk_id": record["chunk_id"],
        "category": record.get("category"),
        "question": q["q"],
        "why_this_chunk": q.get("why_this_chunk", ""),
        "grading": parsed,
        "raw": out if parsed is None else None,
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--pairs", required=True, help="input pairs JSONL (one record per chunk, with 'questions' list)")
    ap.add_argument("--out", required=True, help="output JSONL (one line per (chunk, question) pair)")
    ap.add_argument("--sample", type=int, default=300, help="N pairs to grade (stratified by category)")
    ap.add_argument("--workers", type=int, default=4)
    ap.add_argument("--model", default="opus")
    ap.add_argument("--seed", type=int, default=42)
    args = ap.parse_args()

    pairs_path = Path(args.pairs)
    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    # Load all records (skip malformed lines)
    records = []
    bad = 0
    for i, line in enumerate(pairs_path.read_text(encoding="utf-8").splitlines(), 1):
        if not line.strip(): continue
        try:
            records.append(json.loads(line))
        except Exception:
            bad += 1
    if bad: print(f"[load] skipped {bad} malformed lines", file=sys.stderr)
    print(f"[load] {len(records)} chunk records", file=sys.stderr)

    # Flatten to (record, question) pairs. Normalize schema: Opus uses "question", Gemini/Claude-standard uses "q".
    flat = []
    for r in records:
        for q in r.get("questions", []):
            if "q" not in q and "question" in q:
                q["q"] = q["question"]
            if "q" not in q:
                continue
            flat.append((r, q))
    print(f"[flat] {len(flat)} (chunk, question) pairs", file=sys.stderr)

    # Resume: skip already-graded (by chunk_id + question text)
    graded_keys = set()
    if out_path.exists():
        for line in out_path.read_text(encoding="utf-8").splitlines():
            try:
                d = json.loads(line)
                graded_keys.add((str(d["chunk_id"]), d["question"]))
            except Exception: pass
        print(f"[resume] {len(graded_keys)} already graded", file=sys.stderr)
    flat = [(r, q) for r, q in flat if (str(r["chunk_id"]), q["q"]) not in graded_keys]

    # Stratified sample by category
    rng = random.Random(args.seed)
    if args.sample and args.sample < len(flat):
        by_cat = {}
        for pair in flat:
            cat = pair[0].get("category") or "unknown"
            by_cat.setdefault(cat, []).append(pair)
        for cat in by_cat: rng.shuffle(by_cat[cat])
        # proportional
        total_remaining = sum(len(v) for v in by_cat.values())
        target = args.sample
        chosen = []
        for cat, lst in by_cat.items():
            n_cat = max(1, round(target * len(lst) / total_remaining))
            chosen.extend(lst[:n_cat])
        rng.shuffle(chosen)
        flat = chosen[:target]
        print(f"[sample] stratified to {len(flat)} pairs across {len(by_cat)} categories", file=sys.stderr)

    t0 = time.time()
    write_lock = Lock()
    counters = {"ok": 0, "parse_err": 0, "call_err": 0}

    with out_path.open("a", encoding="utf-8") as f, \
         ThreadPoolExecutor(max_workers=args.workers) as ex:
        futs = {ex.submit(grade_pair, r, q, args.model): (r, q) for r, q in flat}
        done = 0
        for fut in as_completed(futs):
            done += 1
            res = fut.result()
            with write_lock:
                f.write(json.dumps(res, ensure_ascii=False) + "\n"); f.flush()
            if res["grading"] is None:
                if res["raw"]: counters["parse_err"] += 1
                else: counters["call_err"] += 1
            else:
                counters["ok"] += 1
            if done % 10 == 0 or done <= 5:
                rate = done / max(time.time()-t0, 1)
                eta = (len(flat) - done) / max(rate, 0.01)
                print(f"[{done}/{len(flat)}] ok={counters['ok']} parse_err={counters['parse_err']} call_err={counters['call_err']}  rate={rate:.2f}/s  eta={eta/60:.1f}m",
                      file=sys.stderr)

    print(f"\nDONE: ok={counters['ok']} parse_err={counters['parse_err']} call_err={counters['call_err']}  elapsed={time.time()-t0:.0f}s", file=sys.stderr)

    # Summary stats
    summary = analyze(out_path)
    print("\n=== SUMMARY ===", file=sys.stderr)
    print(json.dumps(summary, indent=2), file=sys.stderr)
    (out_path.parent / (out_path.stem + "_summary.json")).write_text(json.dumps(summary, indent=2))


def analyze(out_path: Path) -> dict:
    rows = []
    for line in out_path.read_text(encoding="utf-8").splitlines():
        try: rows.append(json.loads(line))
        except Exception: pass
    graded = [r for r in rows if r.get("grading")]
    if not graded: return {"n": 0}
    n = len(graded)
    ans = sum(1 for r in graded if r["grading"].get("answerable") == 1)
    real = sum(1 for r in graded if r["grading"].get("realistic") == 1)
    spec = sum(1 for r in graded if r["grading"].get("specific") == 1)
    all_three = sum(1 for r in graded if all(r["grading"].get(k) == 1 for k in ("answerable","realistic","specific")))
    from collections import Counter
    comp = Counter(r["grading"].get("complexity","?") for r in graded)
    cat = Counter(r.get("category","?") for r in graded)
    return {
        "n_total": len(rows),
        "n_graded": n,
        "n_parse_fail": len(rows) - n,
        "answerable_pct": round(100*ans/n, 1),
        "realistic_pct": round(100*real/n, 1),
        "specific_pct": round(100*spec/n, 1),
        "all_three_pct": round(100*all_three/n, 1),
        "complexity": dict(comp),
        "complexity_pct": {k: round(100*v/n, 1) for k,v in comp.items()},
        "by_category": dict(cat),
    }


if __name__ == "__main__":
    main()
